// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.ix.shelters.model;

import ar.com.ix.shelters.model.EstadoTarea;

privileged aspect EstadoTarea_Roo_JavaBean {
    
    public String EstadoTarea.getNombre() {
        return this.nombre;
    }
    
    public void EstadoTarea.setNombre(String nombre) {
        this.nombre = nombre;
    }
    
}
