// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.ix.shelters.model;

import ar.com.ix.shelters.model.Localidad;

privileged aspect Localidad_Roo_JavaBean {
    
    public String Localidad.getNombre() {
        return this.nombre;
    }
    
    public void Localidad.setNombre(String nombre) {
        this.nombre = nombre;
    }
    
}
