// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.ix.shelters.model;

import ar.com.ix.shelters.model.Movimiento;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Movimiento_Roo_Configurable {
    
    declare @type: Movimiento: @Configurable;
    
}
