// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.ix.shelters.model;

import ar.com.ix.shelters.model.Provincia;

privileged aspect Provincia_Roo_JavaBean {
    
    public String Provincia.getNombre() {
        return this.nombre;
    }
    
    public void Provincia.setNombre(String nombre) {
        this.nombre = nombre;
    }
    
}
