// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.ix.shelters.model;

import ar.com.ix.shelters.model.Relevamiento;
import javax.persistence.Entity;

privileged aspect Relevamiento_Roo_Jpa_Entity {
    
    declare @type: Relevamiento: @Entity;
    
}
