// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.ix.shelters.web;

import ar.com.ix.shelters.web.ComponenteBean;
import java.io.Serializable;

privileged aspect ComponenteBean_Roo_Serializable {
    
    declare parents: ComponenteBean implements Serializable;
    
    private static final long ComponenteBean.serialVersionUID = 1L;
    
}
