// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.ix.shelters.web;

import ar.com.ix.shelters.web.LocalidadBean;
import java.io.Serializable;

privileged aspect LocalidadBean_Roo_Serializable {
    
    declare parents: LocalidadBean implements Serializable;
    
    private static final long LocalidadBean.serialVersionUID = 1L;
    
}
