// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.ix.shelters.web;

import ar.com.ix.shelters.web.MovimientoBean;
import java.io.Serializable;

privileged aspect MovimientoBean_Roo_Serializable {
    
    declare parents: MovimientoBean implements Serializable;
    
    private static final long MovimientoBean.serialVersionUID = 1L;
    
}
