// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.ix.shelters.web;

import ar.com.ix.shelters.web.ProvinciaBean;
import java.io.Serializable;

privileged aspect ProvinciaBean_Roo_Serializable {
    
    declare parents: ProvinciaBean implements Serializable;
    
    private static final long ProvinciaBean.serialVersionUID = 1L;
    
}
