// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.ix.shelters.web;

import ar.com.ix.shelters.web.RelevamientoBean;
import java.io.Serializable;

privileged aspect RelevamientoBean_Roo_Serializable {
    
    declare parents: RelevamientoBean implements Serializable;
    
    private static final long RelevamientoBean.serialVersionUID = 1L;
    
}
