// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.ix.shelters.web;

import ar.com.ix.shelters.web.TipoNodoBean;
import java.io.Serializable;

privileged aspect TipoNodoBean_Roo_Serializable {
    
    declare parents: TipoNodoBean implements Serializable;
    
    private static final long TipoNodoBean.serialVersionUID = 1L;
    
}
