// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.ix.shelters.web;

import ar.com.ix.shelters.web.TipoInformeBean;
import java.io.Serializable;

privileged aspect TipoInformeBean_Roo_Serializable {
    
    declare parents: TipoInformeBean implements Serializable;
    
    private static final long TipoInformeBean.serialVersionUID = 1L;
    
}
