// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.ix.shelters.web;

import ar.com.ix.shelters.web.UbicacionBean;
import java.io.Serializable;

privileged aspect UbicacionBean_Roo_Serializable {
    
    declare parents: UbicacionBean implements Serializable;
    
    private static final long UbicacionBean.serialVersionUID = 1L;
    
}
