// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.ix.shelters.web;

import ar.com.ix.shelters.web.ZonaBean;
import java.io.Serializable;

privileged aspect ZonaBean_Roo_Serializable {
    
    declare parents: ZonaBean implements Serializable;
    
    private static final long ZonaBean.serialVersionUID = 1L;
    
}
