// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.ix.shelters.web.converter;

import ar.com.ix.shelters.web.converter.TipoNodoConverter;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TipoNodoConverter_Roo_Configurable {
    
    declare @type: TipoNodoConverter: @Configurable;
    
}
